baseURL       = "http://example.org/"
languageCode  = "en-us"
title         = "ALifeLivedFully"
theme         = "roxo-hugo"
summarylength = 25

# Site Menus
[menu]
  # Navbar Menus
  [[menu.nav]]
    name    = "About"
    url     = "about"
    weight  = 1
  [[menu.nav]]
    name    = "Blog"
    url     = "blog"
    weight  = 2
  [[menu.nav]]
    name    = "Portfolio"
    url     = "portfolio"
    weight  = 3
  [[menu.nav]]
    name    = "Services"
    url     = "services"
    weight  = 4
  [[menu.nav]]
    name    = "Contact"
    url     = "contact"
    weight  = 5

# Site Params
[params]
  logo = "images/ALLF.png"
  logo_footer = "images/ALLF-Footer.png"
  favicon_icon = "images/favicon.ico"
  favicon_shortcut_icon = "images/favicon.png"
  custom_stylesheets = []   # [ "scss/my_1.scss", "scss/my_2.scss" ]
  dateFormat = "26 FEB 1994"
  # Meta data
  description = "ALifeLivedFully | Freelance technical consultant"
  author = "ALifeLivedFully"
  # Google Analitycs
  googleAnalitycsID = "Your ID"
  # using self hosted php to mail form submissions
  fabform  = "scripts/mail.php"

  # Contact Form
  [params.contactForm]
    placeholder_name        = "Name"
    placeholder_phone_number         = "Phone Number"
    placeholder_email             = "Email"
    placeholder_project_type      = "Project Type"
    placeholder_about_the_project = "About the Project"
    send_message                  = "Send Message"

    [[params.contactForm.projectType]]
      value = "Web Development"
      title  = "Web Development"
    [[params.contactForm.projectType]]
      value = "Systems Automation"
      title  = "Systems Automation"
    [[params.contactForm.projectType]]
      value = "Self Sufficiency Education"
      title  = "Self Sufficiency Education"
    [[params.contactForm.projectType]]
      value = "Sustainability Education"
      title  = "Sustainability Education"
    [[params.contactForm.projectType]]
      value = "Other"
      title  = "Other"
  
  # Navbar Action Button
  [params.navAction]
    status  = true
    name    = "Contact"
    url     = "contact"
  

  # Banner Section
  [params.banner]
    enable                = true
    background_image      = "images/backgrounds/hero-background.jpg"
    heading               = "ALifeLivedFully"
    tagline               = "A Freelance technical consultant"
    primary_button        = "See My Work"
    primary_button_url    = "portfolio"
    secondary_button      = "Connect with Me"
    secondary_button_url  = "contact"

  [params.blog]
    read_more             = "read more"

  [params.portfolio]
    enable    = true
    title     = "Portfolio"
    subtitle  = "Driven to build and repair anything."
    view_project = "view project"
    more_works = "MORE WORKS"
    scroll_down = "scroll down"

  [params.call_to_action]
    enable              = true
    background_image    = "images/backgrounds/cta-background.jpg"
    title               = "LET’S WORK TOGETHER"
    primary_button      = "Contact Me"
    primary_button_url  = "contact"
    secondary_button    = "See more"
    secondary_button_url = "portfolio"

  [params.footer]
    params.footer.qr_print = true
    # Footer Contact Info
    [params.footer.contactInfo]
      title   = "Contact Info"
      address = "681 17th Ave NE,<br>Minneapolis MN 55413"
      phone   = "+1 507-414-7710"
      email   = "info@ALifeLivedFully.com"
      # Footer Sitemap
      [params.footer.sitemap]
        title   = "Sitemap"
        [[params.footer.sitemap.link]]
          name = "About Company"
          url  = "about"
        [[params.footer.sitemap.link]]
          name = "Blog"
          url  = "blog"
        [[params.footer.sitemap.link]]
          name = "Portfolio"
          url  = "portfolio"
        [[params.footer.sitemap.link]]
          name = "Services"
          url  = "services"
        [[params.footer.sitemap.link]]
          name = "Contact"
          url  = "contact"
      # Footer Social Media
      [params.footer.social]
        title   = "Links"
        [[params.footer.social.link]]
          name = "All My Links"
          url  = "https://links.alifelivedfully.com"
        [[params.footer.social.link]]
          name = "KeyBase"
          url  = "https://keybase.io/alifelivedfully"
        [[params.footer.social.link]]
          name = "GitHub"
          url  = "https://github.com/ALifeLivedFully"
        [[params.footer.social.link]]
          name = "Patreon"
          url  = "https://patreon.com/ALifeLivedFully"
      # Footer Service
      [params.footer.service]
        title       = "ALifeLivedFully"
        description = "Freelance technical consultant, Systems automation, and Self sufficiency education."
      [params.footer.back_to_top]
        description = "Back to top"
